# Vite 8 doesn't support Yarn PnP because of its new OXC transform
nodeLinker: node-modules

# Global cache doesn't work in CI e.g. our multi-stage build Dockerfile also fails
enableGlobalCache: false

# Do not add ^ dependencies, but always add fixed version
defaultSemverRangePrefix: ""
